[package]
name = "twod_arrays"
version = "0.1.0"
authors = ["qadmium <denis.podgorodnichenko@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
