[package]
name = "beautiful_days_at_the_movies"
version = "0.1.0"
authors = ["qadmium <denis.podgorodnichenko+github@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = '0.1.8'
