[package]
name = "extra_long_factorials"
version = "0.1.0"
authors = ["qadmium <denis.podgorodnichenko+github@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.2.0"
text_io = "0.1.8"